#!/usr/bin/env bash
# Configure container so Nginx runs as nginx user listening on port 8080

# Update nginx.conf to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update listening port to 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
