#!/usr/bin/env bash
# Configure container so Nginx runs as nginx user listening on port 8080

sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user/user/g' /etc/nginx/nginx.conf
service nginx restart
