#!/usr/bin/env bash
# Script that configures Nginx to run as nginx user on port 8080

# Update nginx.conf to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change default port from 80 to 8080 in default site config
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default

# Change ownership of nginx directories to nginx user
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx

# Kill any running nginx processes
pkill nginx

# Start nginx as nginx user
su - nginx -s /bin/bash -c "/usr/sbin/nginx"
