#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Ensure the default site symlink exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start nginx (use start instead of restart in case it's not running)
service nginx start
