#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Fix the sites-enabled symlink if broken
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
