#!/usr/bin/env bash
# Run Nginx as nginx user
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
