#!/usr/bin/env bash

# This script transfers a file from the client to a remote server using scp.

# Check if exactly 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file to the user's home directory on the server
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"
=======
# a Bash script that transfers a file from our client to a server
# Requirements:
# - Accepts 4 parameters
#   1. The path to the file to be transferred
#   2. The IP of the server we want to transfer the file to
#   3. The username scp connects with
#   4. The path to the SSH private key that scp uses
# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 4 parameters passed
# - scp must transfer the file to the user home directory ~/
# - Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

