#!/usr/bin/env bash
# Script to install nginx web server and configure homepage

apt-get update -y
apt-get install nginx -y

# Replace default index.html
echo "Holberton School" > /var/www/html/index.html

# Restart nginx (without systemctl)
service nginx restart
